# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-12 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('base', '0106_remove_fuzzy_tm_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleLogAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_roles_log', to=settings.AUTH_USER_MODEL)),
                ('performed_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User roles log',
                'verbose_name_plural': 'Users roles logs',
            },
        ),
    ]
