# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0117_bug_1405256_ftl_delete_duplicates'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='translation',
            index_together=set([('date', 'locale'), ('entity', 'user'), ('locale', 'user', 'entity'), ('entity', 'locale', 'fuzzy'), ('entity', 'locale', 'approved'), ('entity', 'user', 'approved', 'fuzzy')]),
        ),
    ]
